[package]
name = "db-diff-sample"
version = "1.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
dialoguer = "0.10.4"
fake = "2.6.1"
itertools = "0.11.0"
mysql = "16.0.0"
r2d2 = "0.8.6"
r2d2_mysql = "16.0.0"
rand = "0.8.5"
rayon = "1.7.0"
uuid = { version = "1.3.3", features = ["v4"]}
